import type { GirlsWorkingJob } from "./types";

const now = new Date().toISOString();

/** Seed NYC roles women actually want — founder studio can edit & publish more. */
export const SEED_GIRLS_WORKING_JOBS: GirlsWorkingJob[] = [
  {
    id: "gw-fashion-1",
    title: "Studio Assistant",
    company: "Sandy Liang",
    neighborhood: "Lower East Side",
    city: "New York",
    jobType: "fashion",
    description: "Sample pulls, showroom prep, and shoot-day support for a downtown label women obsess over.",
    payLabel: "$18–22/hr",
    schedule: "Part-time · 3 days",
    applyUrl: "https://example.com/apply/sandy-liang",
    published: true,
    featured: true,
    updatedAt: now,
  },
  {
    id: "gw-fashion-2",
    title: "Visual Merchandising Associate",
    company: "Reformation SoHo",
    neighborhood: "SoHo",
    city: "New York",
    jobType: "fashion",
    description: "Floor styling, window moments, and inventory storytelling — fashion eye required.",
    payLabel: "$20/hr + employee discount",
    schedule: "Full-time",
    published: true,
    updatedAt: now,
  },
  {
    id: "gw-cafe-1",
    title: "Barista · Morning Shift",
    company: "Café Gitane",
    neighborhood: "Nolita",
    city: "New York",
    jobType: "cafe",
    description: "Latte art, pastry case, and the kind of regulars who become your people.",
    payLabel: "$16/hr + tips",
    schedule: "Tue–Sat · 7am–2pm",
    published: true,
    featured: true,
    updatedAt: now,
  },
  {
    id: "gw-cafe-2",
    title: "Floor Host",
    company: "Sant Ambroeus",
    neighborhood: "SoHo",
    city: "New York",
    jobType: "cafe",
    description: "Brunch service, reservation flow, and a polished room women trust for solo dates.",
    payLabel: "$18/hr + tips",
    schedule: "Weekends",
    published: true,
    updatedAt: now,
  },
  {
    id: "gw-library-1",
    title: "Reader Services Associate",
    company: "New York Public Library · Stavros",
    neighborhood: "East Village",
    city: "New York",
    jobType: "library",
    description: "Help women find their next obsession — programming support, stacks, and community desk.",
    payLabel: "$19/hr",
    schedule: "Part-time",
    published: true,
    updatedAt: now,
  },
  {
    id: "gw-social-1",
    title: "Social Media Coordinator",
    company: "Glossier HQ",
    neighborhood: "SoHo",
    city: "New York",
    jobType: "social_media",
    description: "Calendar, captions, and community replies for a brand women already live in.",
    payLabel: "$55–65K",
    schedule: "Hybrid",
    published: true,
    featured: true,
    updatedAt: now,
  },
  {
    id: "gw-content-1",
    title: "Content Producer",
    company: "The Wing Alumni Network",
    neighborhood: "Flatiron",
    city: "New York",
    jobType: "content",
    description: "Short-form video, event recaps, and newsletter moments for a women-led community.",
    payLabel: "$60K",
    schedule: "Full-time",
    published: true,
    updatedAt: now,
  },
  {
    id: "gw-influencer-1",
    title: "Brand Partnerships Associate",
    company: "Creator House NYC",
    neighborhood: "Williamsburg",
    city: "New York",
    jobType: "influencer",
    description: "Match women creators with cafés, hotels, and fashion drops — relationship-first.",
    payLabel: "$52K + commission",
    schedule: "Full-time",
    published: true,
    updatedAt: now,
  },
  {
    id: "gw-retail-1",
    title: "Beauty Advisor",
    company: "Sephora · Meatpacking",
    neighborhood: "Meatpacking",
    city: "New York",
    jobType: "retail",
    description: "Consultations, events, and the glow counter women line up for.",
    payLabel: "$17/hr + bonus",
    schedule: "Flexible",
    published: true,
    updatedAt: now,
  },
  {
    id: "gw-wellness-1",
    title: "Front Desk · Pilates Studio",
    company: "SLT Williamsburg",
    neighborhood: "Williamsburg",
    city: "New York",
    jobType: "wellness",
    description: "Class check-in, retail, and the energy of a room full of women showing up for themselves.",
    payLabel: "$18/hr",
    schedule: "Mornings",
    published: true,
    updatedAt: now,
  },
];
