import type { PosterTemplateData } from "./types";

/** Demo BloomBay events — JPG/WebP photo URLs for visual QA of all six templates. */
export const SAMPLE_POSTER_EVENTS: PosterTemplateData[] = [
  {
    id: "demo-dinner-soho",
    template: "dinner",
    title: "Saturday in Soho",
    category: "Supper Club · Dinner Party",
    date: "Sat, Jun 14",
    time: "7:30 PM",
    location: "Sant Ambroeus · SoHo",
    seatsLeft: 4,
    hostName: "BloomBay Hosts",
    imageUrl:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80",
    accentColor: "#c9a66b",
    ctaLabel: "Reserve seat",
  },
  {
    id: "demo-club-run",
    template: "club",
    title: "Morning Run Club",
    category: "BloomBay House",
    date: "Every Saturday",
    time: "7:00 AM",
    location: "Hudson River Park · Pier 45",
    seatsLeft: 12,
    hostName: "Coach Maya",
    memberCount: 248,
    imageUrl:
      "https://images.unsplash.com/photo-1476480862122-209bfaa8efa1?auto=format&fit=crop&w=900&q=80",
    accentColor: "#e85d8a",
    ctaLabel: "Enter club",
  },
  {
    id: "demo-party-roof",
    template: "party",
    title: "Rooftop Bloom Launch",
    category: "Nightlife · Celebration",
    date: "Fri, Jul 4",
    time: "9:00 PM",
    location: "The William Vale · Williamsburg",
    seatsLeft: 18,
    hostName: "BloomBay NYC",
    imageUrl:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=80",
    accentColor: "#ff2d6f",
    ctaLabel: "Get on list",
  },
  {
    id: "demo-museum-whitney",
    template: "museum",
    title: "Evening at the Whitney",
    category: "Gallery · Culture",
    date: "Thu, Jun 26",
    time: "6:00 PM",
    location: "Whitney Museum · Meatpacking",
    seatsLeft: 8,
    hostName: "The Page Turners",
    imageUrl:
      "https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=900&q=80",
    accentColor: "#2a2a32",
    ctaLabel: "View gathering",
  },
  {
    id: "demo-walk-park",
    template: "walk",
    title: "Sunrise in the Park",
    category: "Walk · Casual meetup",
    date: "Sun, Jun 8",
    time: "6:15 AM",
    location: "Central Park · Bethesda Terrace",
    seatsLeft: 6,
    hostName: "Jules",
    imageUrl:
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=80",
    accentColor: "#7eb8a4",
    ctaLabel: "Walk with us",
  },
  {
    id: "demo-wellness-matcha",
    template: "wellness",
    title: "Pilates & Matcha Morning",
    category: "Wellness · Restore",
    date: "Wed, Jun 11",
    time: "8:30 AM",
    location: "Fort Greene · Studio B",
    seatsLeft: 5,
    hostName: "Simone",
    imageUrl:
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=900&q=80",
    accentColor: "#d4a5c8",
    ctaLabel: "Book mat",
  },
];
