import type { PortalOnboardingFlow } from "./types";

export const PORTAL_ONBOARDING_FLOWS: Record<PortalOnboardingFlow["portalId"], PortalOnboardingFlow> = {
  partner: {
    portalId: "partner",
    portalLabel: "Partner portal",
    welcome: "Sell more. Fill seats. Know what's working.",
    accentClass: "po-tour--partner",
    steps: [
      {
        id: "p1",
        title: "Your revenue dashboard",
        body: "Track events hosted, women seated, revenue, and which menu items BloomBay women order most — all in one place.",
        illustration: "revenue",
        tip: "Check dashboard every Monday to plan Boom drops.",
        ctaHref: "/partner",
        ctaLabel: "Open dashboard",
      },
      {
        id: "p2",
        title: "Brand identity & templates",
        body: "Pick a café, restaurant, salon, studio, or venue template. Change colors, upload photos, and publish your About us + menu.",
        illustration: "brand",
        ctaHref: "/partner/brand",
        ctaLabel: "Build your brand",
      },
      {
        id: "p3",
        title: "Edit every caption",
        body: "Hero caption, About slides, and each menu item have editable captions — the copy members see on Eats and in The City.",
        illustration: "brand",
        tip: "Short captions work for Instagram cross-posts too.",
      },
      {
        id: "p4",
        title: "Boom drops — specials & discounts",
        body: "Run % off, buy-one-get-one, or bundle deals. Members see active drops on your page and in Eats.",
        illustration: "drops",
        ctaHref: "/partner/drops",
        ctaLabel: "Create a Boom drop",
      },
      {
        id: "p5",
        title: "Bookings & availability",
        body: "Confirm host events, reply to messages, and keep availability current so BloomBay can fill your room.",
        illustration: "calendar",
        ctaHref: "/partner/bookings",
        ctaLabel: "View bookings",
      },
    ],
  },
  club_owner: {
    portalId: "club_owner",
    portalLabel: "Club Mama portal",
    welcome: "Your club. Your rooms. Not a venue partner portal.",
    accentClass: "po-tour--club",
    steps: [
      {
        id: "c1",
        title: "Clubhouse dashboard",
        body: "Health score, applications, gatherings, and revenue — built for Club Mamas running repeat rooms.",
        illustration: "dashboard",
        ctaHref: "/club-owner/dashboard",
        ctaLabel: "Your dashboard",
      },
      {
        id: "c2",
        title: "Customize your club kit",
        body: "BloomBay objects, poster templates, accent colors, and house rules — members see this when they join.",
        illustration: "brand",
        ctaHref: "/club-owner/customize",
        ctaLabel: "Customize kit",
      },
      {
        id: "c3",
        title: "Event templates",
        body: "Duplicate successful happenings — timeline, budget, checklist — so you don't start from zero.",
        illustration: "calendar",
        ctaHref: "/club-owner/templates",
        ctaLabel: "Event templates",
      },
      {
        id: "c4",
        title: "Gatherings & open seats",
        body: "Publish happenings, hold seats, and welcome women into your club world.",
        illustration: "club",
        ctaHref: "/club-owner/gatherings",
        ctaLabel: "Gatherings",
      },
      {
        id: "c5",
        title: "Applications & members",
        body: "Review who wants in, manage your roster, and keep your club feeling intentional.",
        illustration: "club",
        ctaHref: "/club-owner/applications",
        ctaLabel: "Applications",
      },
    ],
  },
  founder: {
    portalId: "founder",
    portalLabel: "Founder portal",
    welcome: "Mission Control — the whole city in one desk.",
    accentClass: "po-tour--founder",
    steps: [
      {
        id: "f1",
        title: "Mission Control overview",
        body: "Women, clubs, happenings, bloom requests — your daily operating picture.",
        illustration: "mission",
        ctaHref: "/founder/dashboard",
        ctaLabel: "Overview",
      },
      {
        id: "f2",
        title: "Create space",
        body: "Monthly social calendar, layered themes, templates, magazine posts, and Daily Bloom — your content studio.",
        illustration: "create",
        ctaHref: "/founder/create",
        ctaLabel: "Create space",
      },
      {
        id: "f3",
        title: "Portal invites",
        body: "One company login — send invite links so staff land in the right portal automatically.",
        illustration: "mission",
        ctaHref: "/founder/invites",
        ctaLabel: "Send invites",
      },
      {
        id: "f4",
        title: "QA Lab",
        body: "Smoke every portal route on mobile, tablet, and desktop before you ship.",
        illustration: "dashboard",
        ctaHref: "/founder/qa-lab",
        ctaLabel: "Open QA Lab",
      },
      {
        id: "f5",
        title: "Yande, markets & neighborhoods",
        body: "Editorial voice, city expansion, and neighborhood pulse — founder-only tools.",
        illustration: "field",
        ctaHref: "/founder/yande",
        ctaLabel: "Yande desk",
      },
    ],
  },
  admin: {
    portalId: "admin",
    portalLabel: "Operations portal",
    welcome: "Keep the platform safe, fast, and moving.",
    accentClass: "po-tour--admin",
    steps: [
      {
        id: "a1",
        title: "Operations dashboard",
        body: "Applications, safety, verification, and inbox — your moderator and admin queue.",
        illustration: "dashboard",
        ctaHref: "/admin/dashboard",
        ctaLabel: "Dashboard",
      },
      {
        id: "a2",
        title: "Applications & trust",
        body: "Review club and partner applications, verification photos, and safety reports.",
        illustration: "mission",
        ctaHref: "/admin/applications",
        ctaLabel: "Applications",
      },
      {
        id: "a3",
        title: "Partners pipeline",
        body: "Venues and brands in the waitlist — approve partners who'll use Brand + Boom drops.",
        illustration: "brand",
        ctaHref: "/admin/partners",
        ctaLabel: "Partners",
      },
      {
        id: "a4",
        title: "QA Lab",
        body: "Run automated route checks across member, clubhouse, partner, and public pages.",
        illustration: "dashboard",
        ctaHref: "/admin/qa-lab",
        ctaLabel: "QA Lab",
      },
    ],
  },
  curator: {
    portalId: "curator",
    portalLabel: "Curator portal",
    welcome: "Culture in the field — gatherings, women, welcome.",
    accentClass: "po-tour--curator",
    steps: [
      {
        id: "u1",
        title: "Curator dashboard",
        body: "Your gatherings, women welcomed, and upcoming field work — separate from Operations.",
        illustration: "field",
        ctaHref: "/curator/dashboard",
        ctaLabel: "Dashboard",
      },
      {
        id: "u2",
        title: "Host gatherings",
        body: "Confirm rooms, show up IRL, and document proof-of-life for BloomBay marketing.",
        illustration: "calendar",
        ctaHref: "/curator/gatherings",
        ctaLabel: "Gatherings",
      },
      {
        id: "u3",
        title: "Welcome women",
        body: "Recruit and welcome members into clubs — your pay ties to real attendance.",
        illustration: "club",
        ctaHref: "/curator/women",
        ctaLabel: "Women",
      },
      {
        id: "u4",
        title: "Pay & receipts",
        body: "Track curator payouts and upload receipts for field expenses.",
        illustration: "revenue",
        ctaHref: "/curator/pay",
        ctaLabel: "Pay",
      },
    ],
  },
};

export function getOnboardingFlow(portalId: PortalOnboardingFlow["portalId"]): PortalOnboardingFlow {
  return PORTAL_ONBOARDING_FLOWS[portalId];
}
